- name: List all the provision instance
  gather_facts: false
  hosts: localhost
  connection: local
  vars_files:
    - ec2_vars/env.yml
  tasks:
    - name: List all the instance
      ec2_instance_info:
       region: "us-east-2"
       aws_access_key: "{{ AWS_ACCESS_KEY }}"
       aws_secret_key: "{{ AWS_SECRET_KEY }}"
